/*
 * @Author: your name
 * @Date: 2021-03-02 10:19:36
 * @LastEditTime: 2021-03-02 15:06:48
 * @LastEditors: your name
 * @Description: In User Settings Edit
 * @FilePath: /slothjson/src/me_test copy.h
 */
////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __me_test_20210221001932_h__
#define __me_test_20210221001932_h__

#include "slothjson.h"

namespace slothjson {

struct metest_object_t
{
    bool isStarted;
    int8_t mak;
    uint64_t age;
    float amountd;
    double amount;
    std::string str;
    std::vector<int32_t > vec;
    std::map<std::string, std::string > dict;

    metest_object_t();
    metest_object_t& operator=(const metest_object_t& obj_val);
    bool operator==(const metest_object_t& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);
private:
   
};

bool encode(const metest_object_t& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, metest_object_t& obj_val);

} // namespace slothjson

#endif // __me_test_20210221001932_h__