/*
 * @Author: your name
 * @Date: 2021-03-02 10:19:36
 * @LastEditTime: 2021-03-02 15:11:11
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /slothjson/src/me_test copy 2.h
 */
////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __me_test_20210221003122_h__
#define __me_test_20210221003122_h__

#include "jsontypedefs.h"

namespace slothjson {

mt_struct_begin(metest_object_t)
    mt_field(MtBool, isStarted)
    mt_field(MtInt8, mak)
    mt_field(MtInt16, th)
    mt_field(MtInt32, len)
    mt_field(MtInt64, length)
    mt_field(MtDouble, amount)
    mt_field(MtString, str)
    mt_field(MtArray, vec)
    mt_field(MtMap, dict)
mt_struct_end(metest_object_t)

} // namespace slothjson

#endif // __me_test_20210221003122_h__